// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARkeFOybKuc0EWtK2m76iL4vL4sjBvK4w',
    appId: '1:22109678816:web:24db09139ff0c02cd47485',
    messagingSenderId: '22109678816',
    projectId: 'todo-app-cb151',
    authDomain: 'todo-app-cb151.firebaseapp.com',
    storageBucket: 'todo-app-cb151.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcr8Rhvnkg3JUMEQ32eWxzM3JS_bYAnL0',
    appId: '1:22109678816:android:b1ae84db616824ffd47485',
    messagingSenderId: '22109678816',
    projectId: 'todo-app-cb151',
    storageBucket: 'todo-app-cb151.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5NnWpDJjeYTjCoOQoUnsCv16VlpryC5I',
    appId: '1:22109678816:ios:13aa79770400b9c2d47485',
    messagingSenderId: '22109678816',
    projectId: 'todo-app-cb151',
    storageBucket: 'todo-app-cb151.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5NnWpDJjeYTjCoOQoUnsCv16VlpryC5I',
    appId: '1:22109678816:ios:8f73acbef4236c63d47485',
    messagingSenderId: '22109678816',
    projectId: 'todo-app-cb151',
    storageBucket: 'todo-app-cb151.appspot.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
